[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
appload-client = { path = "../../../backend-clients/rust-backend" }
async-trait = "0.1.83"
tokio = { version = "1.42.0", features = ["macros", "rt", "rt-multi-thread"] }

